on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 * * '

name: cron

env:
  GH_TOKEN: ${{ secrets.CRON_TOKEN }}

jobs:
  enable:
    runs-on: macOS-latest

    name: Enable GHA 

    steps:
      - uses: actions/checkout@HEAD

      - name: Keep myself alive every month
        run: |
          git tag v$(date +%Y.%m.%d) || true
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin --tags
