# biweekly reminder on which packages can be released to CRAN
on:
  workflow_dispatch:
    inputs:
      pkg_repo:
        description: 'Github repo of the form user/repo'
        required: false
        type: string
      use_pandoc:
        description: 'Whether to use Pandoc'
        default: false
        type: boolean
  schedule:
    - cron: '0 6 1,15 * *'

name: package-release

jobs:
  package-release:
    runs-on: macOS-latest

    name: Release reminder

    steps:
      - uses: actions/checkout@HEAD

      - uses: actions/checkout@HEAD
        if: github.event.inputs.pkg_repo != ''
        with:
          path: package
          repository: ${{ github.event.inputs.pkg_repo }}

      - uses: r-lib/actions/setup-pandoc@HEAD
        if: github.event.inputs.use_pandoc

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: devel
          http-user-agent: release
          use-public-rspm: true

      - run: Rscript release.R
